server:
  port: 8022
spring:
  application:
    name: rabbitmq-consumer
  #配置rabbitMq 服务器
  rabbitmq:
    host: 39.100.149.36
    port: 5671
    username: guest
    password: guest
    #虚拟host 可以不设置,使用server默认host
    virtual-host: springtest
