server:
  port: 8022
spring:
  application:
    name: rabbitmq-consumer
  #配置rabbitMq 服务器
  rabbitmq:
    host: 39.100.149.36
    port: 5671
    username: guest
    password: guest
    #虚拟host 可以不设置,使用server默认host
    virtual-host: springtest

    #消息确认配置项
    #确认消息已发送到交换机(Exchange)
    publisher-confirm-type: correlated
    #确认消息已发送到队列(Queue)
    publisher-returns: true
#    Deprecated configuration property 'spring.rabbitmq.publisher-confirms'
